import Link from "next/link";
import { ArrowDown, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PlayerSearch } from "@/components/players/player-search";
import { CATEGORIES, CATEGORY_DEFAULT_SORT, POSITIONS, categoryColumns, parsePlayerFilters } from "@/lib/players/filters";
import { getAvailableSeasons, getPlayerLeaders } from "@/lib/players/queries";
import type { StatColumn, } from "@/lib/players/filters";

const first = (input: string | string[] | undefined) => Array.isArray(input) ? input[0] : input;
function formatStat(input: unknown, column: StatColumn) { if (input === null || input === undefined || input === "") return "—"; const value = Number(input) * (column.percentage ? 100 : 1); return value.toLocaleString(undefined, { minimumFractionDigits: column.digits ?? 0, maximumFractionDigits: column.digits ?? 0 }) + (column.percentage ? "%" : ""); }

export default async function PlayersPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const filters = parsePlayerFilters(params);
  let seasons: number[] = []; let error = "";
  try { seasons = await getAvailableSeasons(filters.seasonType); } catch (cause) { console.error(cause); error = "Historical statistics are unavailable. Apply the latest player-stat migration and verify the import."; }
  const requestedSeason = Number.parseInt(first(params.season) ?? "", 10);
  const season = seasons.includes(requestedSeason) ? requestedSeason : seasons[0];
  let result = { rows: [], total: 0, pageSize: 50 } as Awaited<ReturnType<typeof getPlayerLeaders>>;
  if (season && !error) { try { result = await getPlayerLeaders({ season, ...filters }); } catch (cause) { console.error(cause); error = "The leaderboard query failed. Apply the latest migration before using the expanded stat explorer."; } }
  const columns = categoryColumns(filters.category, filters.scoring, filters.position); const totalPages = Math.max(1, Math.ceil(result.total / result.pageSize));
  const href = (changes: Record<string, string | number>) => { const query = new URLSearchParams({ season: String(season ?? ""), scoring: filters.scoring, position: filters.position, seasonType: filters.seasonType, category: filters.category, sort: filters.sort, view: filters.view, page: String(filters.page), ...Object.fromEntries(Object.entries(changes).map(([key, item]) => [key, String(item)])) }); return `/players?${query}`; };
  return <div className="mx-auto max-w-7xl">
    <header><p className="text-sm font-bold tracking-widest text-cyan-300">PLAYER EXPLORER</p><h1 className="mt-1 text-3xl font-black">Historical NFL & Fantasy Statistics</h1><p className="mt-2 text-slate-400">Position-aware season totals and weighted efficiency metrics from 2012–2025.</p></header>
    <div className="mt-6"><PlayerSearch /></div>
    <Card className="mt-6"><form className="grid gap-4 sm:grid-cols-4"><input type="hidden" name="view" value={filters.view} /><input type="hidden" name="category" value={filters.category} /><input type="hidden" name="sort" value={filters.sort} /><label className="text-sm text-slate-400">Season<select name="season" defaultValue={season} className="mt-1 w-full rounded-lg border bg-slate-950 px-3 py-2 text-white">{seasons.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm text-slate-400">Scoring<select name="scoring" defaultValue={filters.scoring} className="mt-1 w-full rounded-lg border bg-slate-950 px-3 py-2 text-white"><option value="ppr">PPR</option><option value="half_ppr">Half PPR</option><option value="standard">Standard</option></select></label><label className="text-sm text-slate-400">Season type<select name="seasonType" defaultValue={filters.seasonType} className="mt-1 w-full rounded-lg border bg-slate-950 px-3 py-2 text-white"><option value="REG">Regular Season</option><option value="POST">Postseason</option></select></label><Button className="self-end">Apply filters</Button></form><div className="mt-5 flex flex-wrap gap-2">{POSITIONS.map((position) => <Link key={position} href={href({ position, page: 1 })} className={`rounded-lg px-3 py-2 text-sm font-semibold ${filters.position === position ? "bg-cyan-400 text-slate-950" : "bg-slate-800 text-slate-300 hover:bg-slate-700"}`}>{position}</Link>)}</div></Card>
    <div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div className="flex gap-5"><Link href={href({ view: "leaders", page: 1 })} className={filters.view === "leaders" ? "border-b-2 border-cyan-300 pb-2 font-bold" : "pb-2 text-slate-400"}>Leaders</Link><Link href={href({ view: "all", page: 1 })} className={filters.view === "all" ? "border-b-2 border-cyan-300 pb-2 font-bold" : "pb-2 text-slate-400"}>All Players</Link></div>{season && <p className="text-sm text-slate-400">{result.total.toLocaleString()} fantasy players · {season} {filters.seasonType}</p>}</div>
    <nav className="mt-4 flex gap-2 overflow-x-auto pb-1">{CATEGORIES.map((category) => <Link key={category} href={href({ category, sort: CATEGORY_DEFAULT_SORT[category], view: "leaders", page: 1 })} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-semibold capitalize ${filters.category === category ? "bg-slate-100 text-slate-950" : "bg-slate-900 text-slate-300"}`}>{category}</Link>)}</nav>
    {error ? <Card className="mt-4 text-center"><h2 className="font-bold">Player data unavailable</h2><p className="mt-2 text-slate-400">{error}</p></Card> : result.rows.length ? <Card className="mt-4 overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-950/80 text-left text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">Player</th><th className="px-4 py-3">Pos</th><th className="px-4 py-3">Team</th>{columns.map((column) => <SortHead key={column.label} column={column} active={filters.sort === column.sort} href={href({ sort: column.sort, view: "leaders", page: 1 })} />)}</tr></thead><tbody className="divide-y divide-slate-800">{result.rows.map((row, index) => <tr key={row.player_id} className="hover:bg-slate-800/50"><td className="px-4 py-3 font-mono text-slate-500">{(filters.page - 1) * result.pageSize + index + 1}</td><td className="px-4 py-3"><Link className="font-bold hover:text-cyan-300" href={`/players/${row.player_id}?season=${season}&scoring=${filters.scoring}&seasonType=${filters.seasonType}`}>{row.full_name}</Link></td><td className="px-4 py-3"><span className="rounded bg-cyan-400/10 px-2 py-1 font-bold text-cyan-200">{row.historical_position || "—"}</span></td><td className="px-4 py-3 text-slate-400">{row.season_teams || row.current_team || "—"}</td>{columns.map((column) => <td key={column.label} className={`px-4 py-3 ${filters.sort === column.sort ? "font-bold text-cyan-300" : ""}`}>{formatStat(row[column.key], column)}</td>)}</tr>)}</tbody></table></div></Card> : <Card className="mt-4 text-center"><h2 className="font-bold">No player statistics found</h2><p className="mt-2 text-slate-400">Try another season, season type, position, or stat category.</p></Card>}
    {!error && result.total > result.pageSize && <nav className="mt-5 flex items-center justify-between"><Link aria-disabled={filters.page <= 1} className={`flex items-center gap-1 text-sm ${filters.page <= 1 ? "pointer-events-none text-slate-600" : "text-cyan-300"}`} href={href({ page: filters.page - 1 })}><ChevronLeft size={16} /> Previous</Link><span className="text-sm text-slate-400">Page {filters.page} of {totalPages}</span><Link aria-disabled={filters.page >= totalPages} className={`flex items-center gap-1 text-sm ${filters.page >= totalPages ? "pointer-events-none text-slate-600" : "text-cyan-300"}`} href={href({ page: filters.page + 1 })}>Next <ChevronRight size={16} /></Link></nav>}
    <p className="mt-5 text-xs text-slate-500">nflverse is the statistical source. Efficiency rates are derived from season totals. Snap, pressure, and red-zone usage display as unavailable until a separate trusted source is integrated.</p>
  </div>;
}

function SortHead({ column, active, href }: { column: StatColumn; active: boolean; href: string }) { return <th className="px-4 py-3"><Link className={`inline-flex items-center gap-1 ${active ? "text-cyan-300" : ""}`} href={href}>{column.label}{active && <ArrowDown size={13} />}</Link></th>; }
